deployment:
  tasks:
    - export DEPLOYPATH=/home/vnccbvta/public_html/
    - /bin/cp -rf images $DEPLOYPATH
    - /bin/cp -rf wp-content $DEPLOYPATH
    - /bin/cp -r /home/vnccbvta/repositories/gzdental/* $DEPLOYPATH